---
openclaw_install: True
openclaw_enabled: True

openclaw_dir: /opt/iiab/openclaw
openclaw_repo: https://github.com/deldesir/openclaw.git
openclaw_branch: main
openclaw_user: iiab-admin
openclaw_port: 3030
rapidpro_inbound_url: "http://localhost:8000/c/ex/UUID/receive"
openclaw_admin_token: ""
rapidpro_auth_token: ""
