---
- name: Create .env file from template (Legacy support)
  template:
    src: .env.j2
    dest: "{{ ai_middleware_dir }}/.env"
    owner: "{{ ai_middleware_user }}"
    group: "{{ ai_middleware_user }}"
    mode: '0600'
  become: yes
  notify: restart ai-middleware




