---
# Defaults for the rapidpro role


rapidpro_db_pass: "temba"
nodejs_version: "24"
rapidpro_dir: "/opt/iiab/rapidpro"
rapidpro_install: True
rapidpro_enabled: True

admin_email: "admin@box.lan"
admin_password: "changeme"



rapidpro_url: /rp
