---
# Defaults for the rapidpro role


python_version: "3.13.5"
rapidpro_db_name: "temba"
rapidpro_db_user: "temba"
rapidpro_db_pass: ""
nodejs_version: "24"
rapidpro_dir: "/opt/iiab/rapidpro"
rapidpro_install: True
rapidpro_enabled: True

admin_email: "admin@box.lan"
rapidpro_admin_password: ""



rapidpro_url: /rp
rapidpro_drop_db_on_reinstall: false
rapidpro_force_drop_db: false

wuzapi_install: True

# Prebuilt Assets Strategy (Performance/Stability on ARM64)
rapidpro_use_prebuilt_assets: false
rapidpro_assets_version: "v1.0.0"
rapidpro_assets_url: "https://github.com/deldesir/rapidpro/releases/download/{{ rapidpro_assets_version }}/rapidpro-assets-{{ rapidpro_assets_version }}.tar.gz"
wuzapi_enabled: True
wuzapi_port: 8095

wuzapi_admintoken: ""
rapidpro_secret_key: ""
