---
# Defaults for the rapidpro role


python_version: "3.13.5"
rapidpro_db_name: "temba"
rapidpro_db_user: "temba"
rapidpro_db_pass: "temba"
nodejs_version: "24"
rapidpro_dir: "/opt/iiab/rapidpro"
rapidpro_install: True
rapidpro_enabled: True

admin_email: "admin@box.lan"
admin_password: "changeme"



rapidpro_url: /rp
rapidpro_drop_db_on_reinstall: false
rapidpro_force_drop_db: false

